import type { User, Pact, Room, EncouragementTemplate, SupporterActivity } from './types'

export const MOCK_USER: User = {
  id: 'user-001',
  name: 'Alex Chen',
  email: 'alex@gropact.com',
  bio: 'Lifelong learner building better habits, one pact at a time.',
  joinedDate: '2025-12-01T00:00:00.000Z',
  currentStreak: 4,
  longestStreak: 12,
  completionRate: 72,
  totalPacts: 3,
  completedPacts: 1,
  tier: 'free',
  trustScore: 78,
  totalVerifications: 7,
  supporterOf: ['pact-ext-001'],
}

export const MOCK_PACTS: Pact[] = [
  {
    id: 'pact-001',
    userId: 'user-001',
    title: 'Run a 5K in Under 30 Minutes',
    description: 'Train consistently to improve my running pace and endurance, building up to completing a 5K race in under 30 minutes by the end of the month.',
    identityStatement: 'I am a dedicated runner who shows up for myself, rain or shine.',
    startDate: '2026-02-01T00:00:00.000Z',
    endDate: '2026-03-01T00:00:00.000Z',
    status: 'active',
    category: 'Fitness',
    verificationMethod: 'mixed',
    supporters: [
      {
        id: 'sup-001',
        name: 'Jordan',
        feedback: 'Great progress on your intervals! Keep pushing the pace gradually.',
        addedDate: '2026-02-01T00:00:00.000Z',
        trustScore: 85,
        verificationsCompleted: 4,
        encouragementsSent: 8,
        role: 'accountability',
      },
      {
        id: 'sup-002',
        name: 'Sam',
        feedback: 'Remember to warm up properly, you seemed tight last session.',
        addedDate: '2026-02-02T00:00:00.000Z',
        trustScore: 72,
        verificationsCompleted: 2,
        encouragementsSent: 5,
        role: 'verifier',
      },
    ],
    microGoals: [
      {
        id: 'mg-001',
        goalText: 'Complete a 3K tempo run at target 5K pace',
        difficulty: 'medium',
        dueDate: '2026-02-20T00:00:00.000Z',
        reasoning: 'Building pace awareness at race speed will prepare your body for sustained effort.',
        measurableOutcome: 'Finish 3K in under 18 minutes',
        completed: true,
        completedDate: '2026-02-19T00:00:00.000Z',
      },
      {
        id: 'mg-002',
        goalText: 'Do 6x400m interval sprints with 90s rest',
        difficulty: 'hard',
        dueDate: '2026-02-22T00:00:00.000Z',
        reasoning: 'High-intensity intervals improve VO2 max and leg turnover speed.',
        measurableOutcome: 'Complete all 6 intervals under 1:50 each',
        completed: false,
      },
      {
        id: 'mg-003',
        goalText: 'Perform 20 minutes of dynamic stretching and foam rolling',
        difficulty: 'easy',
        dueDate: '2026-02-19T00:00:00.000Z',
        reasoning: 'Recovery prevents injury and keeps momentum going.',
        measurableOutcome: 'Complete full stretching routine without skipping',
        completed: true,
        completedDate: '2026-02-18T00:00:00.000Z',
      },
      {
        id: 'mg-004',
        goalText: 'Run a full 5K at comfortable pace',
        difficulty: 'medium',
        dueDate: '2026-02-24T00:00:00.000Z',
        reasoning: 'Distance practice builds endurance and mental confidence.',
        measurableOutcome: 'Complete 5K without walking breaks',
        completed: false,
      },
    ],
    nudges: [
      { nudgeText: 'Lay out your running gear the night before -- removing friction makes starting easier.', behavioralPrinciple: 'Friction Reduction' },
      { nudgeText: 'After each run, write one sentence about how you felt. Tracking emotions builds intrinsic motivation.', behavioralPrinciple: 'Reflective Practice' },
      { nudgeText: 'Tell Jordan your next run time so they can check in with you afterward.', behavioralPrinciple: 'Social Accountability' },
    ],
    weeklyPlan: [
      { day: 'Monday', microGoal: 'Dynamic stretching and foam rolling (20 min)', reminder: 'Recovery is training too. Your muscles need this.', supporterPrompt: 'Ask Sam for stretching tips they mentioned.', completed: true },
      { day: 'Tuesday', microGoal: 'Tempo run: 3K at target pace', reminder: 'Focus on breathing rhythm, not speed at the start.', supporterPrompt: 'Share your time with Jordan after the run.', completed: true },
      { day: 'Wednesday', microGoal: 'Rest day with light walking', reminder: 'Rest is strategic, not lazy. Trust the process.', supporterPrompt: 'Check in with your supporters about how you feel.', completed: true },
      { day: 'Thursday', microGoal: 'Interval sprints: 6x400m', reminder: 'Push hard on sprints, recover fully between sets.', supporterPrompt: 'Ask Jordan to join you for this session if possible.', completed: false },
      { day: 'Friday', microGoal: 'Easy 2K jog and stretching', reminder: 'Keep it light today. Tomorrow is your big run.', supporterPrompt: 'Let Sam know you are on track this week.', completed: false },
      { day: 'Saturday', microGoal: 'Full 5K run at comfortable pace', reminder: 'This is your confidence builder. No pressure on time.', supporterPrompt: 'Invite Jordan and Sam to cheer you on or join!', completed: false },
      { day: 'Sunday', microGoal: 'Rest and reflection', reminder: 'Write about your week. Celebrate what you achieved.', supporterPrompt: 'Share your weekly summary with your supporters.', completed: false },
    ],
    checkIns: [
      {
        id: 'ci-001',
        date: '2026-02-17T00:00:00.000Z',
        note: 'Ran 2.5K in 16 min. Felt strong on the first half but faded a bit.',
        mood: 'good',
        completedGoals: ['mg-003'],
      },
      {
        id: 'ci-002',
        date: '2026-02-16T00:00:00.000Z',
        note: 'Completed interval training. Legs were burning but pushed through all sets.',
        mood: 'great',
        completedGoals: [],
      },
      {
        id: 'ci-003',
        date: '2026-02-15T00:00:00.000Z',
        note: 'Rested due to rain. Did some indoor stretching instead.',
        mood: 'okay',
        completedGoals: [],
      },
    ],
    aiPlan: {
      behavioralState: 'consistent',
      identityAffirmation: 'You are a dedicated runner who shows up for yourself, rain or shine. Your consistency over the past 4 days proves that this goal is not just a wish -- it is who you are becoming.',
      microGoals: [],
      nudges: [],
      weeklyPlan: [],
      explanations: {
        pactInterpretation: 'Your pact focuses on progressive running improvement with a clear time-based target.',
        behaviorInsights: 'Your 4-day streak and 72% completion rate indicate a consistent pattern with occasional dips.',
        supporterInsights: 'Jordan provides performance-focused encouragement while Sam offers practical safety advice.',
      },
      difficultyDistribution: { easyPercent: 25, mediumPercent: 50, hardPercent: 25 },
    },
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-02-17T00:00:00.000Z',
    streak: 4,
    completionRate: 50,
    behavioralState: 'consistent',
    identityAffirmation: 'You are a dedicated runner who shows up for yourself, rain or shine.',
    verifications: [
      {
        id: 'v-001',
        pactId: 'pact-001',
        type: 'photo',
        status: 'verified',
        evidence: 'Post-run selfie with 3K tempo run stats on watch showing 17:45',
        verifiedBy: 'Jordan',
        verifiedAt: '2026-02-19T18:30:00.000Z',
        createdAt: '2026-02-19T17:00:00.000Z',
        note: 'Crushed the tempo run!',
      },
      {
        id: 'v-002',
        pactId: 'pact-001',
        type: 'supporter_confirm',
        status: 'verified',
        evidence: 'Sam confirmed stretching session via text',
        verifiedBy: 'Sam',
        verifiedAt: '2026-02-18T20:00:00.000Z',
        createdAt: '2026-02-18T19:00:00.000Z',
      },
      {
        id: 'v-003',
        pactId: 'pact-001',
        type: 'self_report',
        status: 'pending',
        evidence: 'Completed interval training at the track. Felt strong through all 6 sets.',
        createdAt: '2026-02-17T18:00:00.000Z',
        note: 'Waiting for Jordan to confirm',
      },
    ],
    weeklyReflections: [
      {
        id: 'wr-001',
        pactId: 'pact-001',
        weekNumber: 2,
        weekStartDate: '2026-02-10T00:00:00.000Z',
        whatWentWell: 'Hit a new 3K personal best and maintained consistency for the full week. Recovery days felt earned rather than lazy.',
        whatWasChallenging: 'Pushing through the last two intervals on Thursday was brutal. Also struggled with motivation when it rained on Wednesday.',
        lessonsLearned: 'Indoor alternatives are key for rainy days. Pre-planning backup workouts removes the decision fatigue that leads to skipping.',
        recommitment: 'I recommit to showing up for every scheduled run this week, even if I have to modify the workout.',
        energyLevel: 4,
        supporterHelpfulness: 4,
        mood: 'energized',
        createdAt: '2026-02-16T20:00:00.000Z',
      },
    ],
    progressCards: [
      {
        id: 'pc-001',
        pactId: 'pact-001',
        title: '3K Personal Best',
        description: 'Achieved a new personal best on the 3K tempo run, completing it in 17:45.',
        milestone: 'First 3K under 18 minutes',
        verified: true,
        verificationMethod: 'photo',
        stats: {
          streakDays: 4,
          goalsCompleted: 2,
          totalGoals: 4,
          completionRate: 50,
        },
        createdAt: '2026-02-19T19:00:00.000Z',
        shared: false,
      },
    ],
  },
  {
    id: 'pact-002',
    userId: 'user-001',
    title: 'Read 12 Books This Year',
    description: 'Build a consistent reading habit by finishing one book per month, focusing on personal growth and science topics.',
    identityStatement: 'I am a curious reader who invests in knowledge every day.',
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T00:00:00.000Z',
    status: 'active',
    category: 'Learning',
    verificationMethod: 'supporter',
    supporters: [
      {
        id: 'sup-003',
        name: 'Maya',
        feedback: 'Love your book picks! Have you considered Atomic Habits? It ties into your goals.',
        addedDate: '2026-01-05T00:00:00.000Z',
        trustScore: 90,
        verificationsCompleted: 3,
        encouragementsSent: 12,
        role: 'encourager',
      },
    ],
    microGoals: [
      {
        id: 'mg-005',
        goalText: 'Read 30 pages per day for 7 consecutive days',
        difficulty: 'medium',
        dueDate: '2026-02-25T00:00:00.000Z',
        reasoning: 'Consistent daily reading builds the habit loop.',
        measurableOutcome: '210 pages read by end of week',
        completed: false,
      },
      {
        id: 'mg-006',
        goalText: 'Write a one-paragraph summary of current book chapter',
        difficulty: 'easy',
        dueDate: '2026-02-21T00:00:00.000Z',
        reasoning: 'Summarizing deepens comprehension and retention.',
        measurableOutcome: 'Written summary shared with Maya',
        completed: true,
        completedDate: '2026-02-20T00:00:00.000Z',
      },
      {
        id: 'mg-007',
        goalText: 'Finish current book and start next one',
        difficulty: 'hard',
        dueDate: '2026-02-28T00:00:00.000Z',
        reasoning: 'Transitioning between books keeps momentum and excitement.',
        measurableOutcome: 'Book 2 completed, Book 3 started',
        completed: false,
      },
    ],
    nudges: [
      { nudgeText: 'Keep your current book on your nightstand so it is the last thing you see before sleep.', behavioralPrinciple: 'Environment Design' },
      { nudgeText: 'Replace 15 minutes of scrolling with reading after lunch.', behavioralPrinciple: 'Habit Stacking' },
    ],
    weeklyPlan: [
      { day: 'Monday', microGoal: 'Read 30 pages', reminder: 'Start with just one page. Momentum will carry you.', supporterPrompt: 'Tell Maya what chapter you are on.', completed: true },
      { day: 'Tuesday', microGoal: 'Read 30 pages', reminder: 'Try reading at a new location today.', supporterPrompt: 'Share a quote you liked.', completed: true },
      { day: 'Wednesday', microGoal: 'Read 30 pages and write a summary', reminder: 'Summarizing what you read cements it.', supporterPrompt: 'Send your summary to Maya.', completed: false },
      { day: 'Thursday', microGoal: 'Read 30 pages', reminder: 'Consistency over intensity.', supporterPrompt: 'Ask Maya for recommendations.', completed: false },
      { day: 'Friday', microGoal: 'Read 30 pages', reminder: 'Almost done for the week!', supporterPrompt: 'Share your progress update.', completed: false },
      { day: 'Saturday', microGoal: 'Finish remaining chapters or free read', reminder: 'Enjoy the journey.', supporterPrompt: 'Discuss the book with Maya.', completed: false },
      { day: 'Sunday', microGoal: 'Reflect and plan next book', reminder: 'What did this book teach you?', supporterPrompt: 'Post a mini review for the group.', completed: false },
    ],
    checkIns: [
      {
        id: 'ci-004',
        date: '2026-02-17T00:00:00.000Z',
        note: 'Read 35 pages today. The chapter on habit loops was fascinating.',
        mood: 'great',
        completedGoals: ['mg-006'],
      },
      {
        id: 'ci-005',
        date: '2026-02-15T00:00:00.000Z',
        note: 'Only managed 15 pages but took detailed notes.',
        mood: 'okay',
        completedGoals: [],
      },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-02-17T00:00:00.000Z',
    streak: 2,
    completionRate: 33,
    verifications: [
      {
        id: 'v-004',
        pactId: 'pact-002',
        type: 'supporter_confirm',
        status: 'verified',
        evidence: 'Maya confirmed chapter summary was shared and discussed',
        verifiedBy: 'Maya',
        verifiedAt: '2026-02-20T21:00:00.000Z',
        createdAt: '2026-02-20T19:00:00.000Z',
      },
      {
        id: 'v-005',
        pactId: 'pact-002',
        type: 'self_report',
        status: 'pending',
        evidence: 'Read 35 pages of Deep Work, took notes on focus techniques',
        createdAt: '2026-02-17T22:00:00.000Z',
      },
    ],
    weeklyReflections: [
      {
        id: 'wr-002',
        pactId: 'pact-002',
        weekNumber: 7,
        weekStartDate: '2026-02-10T00:00:00.000Z',
        whatWentWell: 'Found a great reading routine after lunch. The 30-page daily target feels sustainable and I exceeded it twice.',
        whatWasChallenging: 'Some chapters were dense and slowed my pace. Tempted to skim but committed to deep reading.',
        lessonsLearned: 'Dense material takes longer but yields more insights. Adjusting pace expectations for challenging books prevents frustration.',
        recommitment: 'I recommit to reading 30 pages daily, allowing flexibility on dense material without guilt.',
        energyLevel: 3,
        supporterHelpfulness: 5,
        mood: 'steady',
        createdAt: '2026-02-16T19:00:00.000Z',
      },
    ],
    progressCards: [],
  },
  {
    id: 'pact-003',
    userId: 'user-001',
    title: 'Learn Guitar Basics',
    description: 'Learn fundamental guitar chords, strumming patterns, and play 3 songs from start to finish.',
    identityStatement: 'I am a musician who embraces the learning process with patience.',
    startDate: '2025-12-01T00:00:00.000Z',
    endDate: '2026-01-31T00:00:00.000Z',
    status: 'completed',
    category: 'Creative',
    verificationMethod: 'photo',
    supporters: [
      {
        id: 'sup-004',
        name: 'Riley',
        feedback: 'Your chord transitions are getting so much smoother!',
        addedDate: '2025-12-05T00:00:00.000Z',
        trustScore: 88,
        verificationsCompleted: 5,
        encouragementsSent: 15,
        role: 'all',
      },
    ],
    microGoals: [
      {
        id: 'mg-008',
        goalText: 'Learn and memorize 5 basic open chords (C, G, D, Em, Am)',
        difficulty: 'medium',
        dueDate: '2025-12-15T00:00:00.000Z',
        reasoning: 'These chords form the foundation of thousands of songs.',
        measurableOutcome: 'Play all 5 chords from memory without hesitation',
        completed: true,
        completedDate: '2025-12-14T00:00:00.000Z',
      },
      {
        id: 'mg-009',
        goalText: 'Practice chord transitions for 15 minutes daily',
        difficulty: 'easy',
        dueDate: '2025-12-31T00:00:00.000Z',
        reasoning: 'Smooth transitions are key to playing actual songs.',
        measurableOutcome: 'Transition between any two chords in under 2 seconds',
        completed: true,
        completedDate: '2025-12-28T00:00:00.000Z',
      },
      {
        id: 'mg-010',
        goalText: 'Learn and perform 3 complete songs',
        difficulty: 'hard',
        dueDate: '2026-01-31T00:00:00.000Z',
        reasoning: 'Playing complete songs integrates all skills and builds confidence.',
        measurableOutcome: 'Record yourself playing 3 songs and share with Riley',
        completed: true,
        completedDate: '2026-01-29T00:00:00.000Z',
      },
    ],
    nudges: [
      { nudgeText: 'Keep your guitar on a stand in your living room, not in a case.', behavioralPrinciple: 'Friction Reduction' },
      { nudgeText: 'Practice right after your morning coffee for habit consistency.', behavioralPrinciple: 'Habit Stacking' },
    ],
    weeklyPlan: [
      { day: 'Monday', microGoal: 'Chord practice (15 min)', reminder: 'Focus on clean sound.', supporterPrompt: 'Show Riley your progress.', completed: true },
      { day: 'Tuesday', microGoal: 'Strumming patterns (15 min)', reminder: 'Keep a steady rhythm.', supporterPrompt: 'Ask Riley for song suggestions.', completed: true },
      { day: 'Wednesday', microGoal: 'Song practice (20 min)', reminder: 'Slow is smooth, smooth is fast.', supporterPrompt: 'Share a short clip.', completed: true },
      { day: 'Thursday', microGoal: 'Chord transitions (15 min)', reminder: 'Focus on the difficult ones.', supporterPrompt: 'Check in with Riley.', completed: true },
      { day: 'Friday', microGoal: 'Full song run-through', reminder: 'Play through mistakes.', supporterPrompt: 'Perform for someone.', completed: true },
      { day: 'Saturday', microGoal: 'Learn a new technique', reminder: 'Try fingerpicking.', supporterPrompt: 'Discuss new goals.', completed: true },
      { day: 'Sunday', microGoal: 'Free play and reflect', reminder: 'Enjoy the music.', supporterPrompt: 'Share your week.', completed: true },
    ],
    checkIns: [],
    createdAt: '2025-12-01T00:00:00.000Z',
    updatedAt: '2026-01-29T00:00:00.000Z',
    streak: 0,
    completionRate: 100,
    behavioralState: 'consistent',
    verifications: [
      {
        id: 'v-006',
        pactId: 'pact-003',
        type: 'photo',
        status: 'verified',
        evidence: 'Video recording of playing Wonderwall, Let It Be, and Horse With No Name',
        verifiedBy: 'Riley',
        verifiedAt: '2026-01-29T20:00:00.000Z',
        createdAt: '2026-01-29T18:00:00.000Z',
        note: 'All 3 songs played from start to finish!',
      },
    ],
    weeklyReflections: [],
    progressCards: [
      {
        id: 'pc-002',
        pactId: 'pact-003',
        title: 'Guitar Basics Mastered',
        description: 'Completed all micro-goals: learned 5 chords, mastered transitions, and performed 3 complete songs.',
        milestone: 'Pact Completed - 100%',
        verified: true,
        verificationMethod: 'photo',
        stats: {
          streakDays: 14,
          goalsCompleted: 3,
          totalGoals: 3,
          completionRate: 100,
        },
        createdAt: '2026-01-30T10:00:00.000Z',
        shared: true,
      },
    ],
  },
]

export const MOCK_ROOMS: Room[] = [
  {
    id: 'room-001',
    name: 'Runners United',
    description: 'A supportive community for runners of all levels. Share your runs, get advice, and stay motivated together.',
    category: 'Fitness',
    memberCount: 24,
    members: ['user-001', 'user-002', 'user-003'],
    posts: [
      {
        id: 'post-001',
        userId: 'user-002',
        userName: 'Jordan Lee',
        content: 'Just finished my first half marathon! 2:15:30. Never thought I could do it when I started running 6 months ago. Keep pushing, everyone!',
        createdAt: '2026-02-17T14:30:00.000Z',
        likes: 12,
        likedBy: ['user-001', 'user-003'],
        type: 'milestone',
      },
      {
        id: 'post-002',
        userId: 'user-003',
        userName: 'Priya Sharma',
        content: 'Any tips for running in cold weather? I lose motivation when it drops below 5 degrees.',
        createdAt: '2026-02-16T09:15:00.000Z',
        likes: 5,
        likedBy: ['user-001'],
        type: 'question',
      },
      {
        id: 'post-003',
        userId: 'user-001',
        userName: 'Alex Chen',
        content: 'Hit a new 3K personal best today: 17:45! Interval training is really paying off.',
        createdAt: '2026-02-15T18:00:00.000Z',
        likes: 8,
        likedBy: ['user-002', 'user-003'],
        type: 'update',
      },
    ],
    createdAt: '2025-11-01T00:00:00.000Z',
    isPublic: true,
    icon: 'FiActivity',
    type: 'community',
    challenges: [
      {
        id: 'ch-001',
        roomId: 'room-001',
        title: '30-Day Run Streak',
        description: 'Run at least 1 mile every day for 30 days. No excuses, no rest days. Walk-runs count!',
        creatorName: 'Jordan Lee',
        startDate: '2026-02-15T00:00:00.000Z',
        endDate: '2026-03-16T00:00:00.000Z',
        verificationMethod: 'self_report',
        participants: [
          {
            userId: 'user-001',
            userName: 'Alex Chen',
            joinedAt: '2026-02-15T08:00:00.000Z',
            progress: 13,
            completedMilestones: ['cm-001'],
            verified: false,
          },
          {
            userId: 'user-002',
            userName: 'Jordan Lee',
            joinedAt: '2026-02-15T06:00:00.000Z',
            progress: 20,
            completedMilestones: ['cm-001', 'cm-002'],
            verified: true,
          },
        ],
        milestones: [
          {
            id: 'cm-001',
            title: 'Week 1 Complete',
            description: 'Run every day for 7 consecutive days',
            dueDate: '2026-02-22T00:00:00.000Z',
            verificationRequired: false,
          },
          {
            id: 'cm-002',
            title: 'Halfway There',
            description: 'Complete 15 consecutive days of running',
            dueDate: '2026-03-01T00:00:00.000Z',
            verificationRequired: true,
          },
          {
            id: 'cm-003',
            title: 'Full 30 Days',
            description: 'Complete the full 30-day streak',
            dueDate: '2026-03-16T00:00:00.000Z',
            verificationRequired: true,
          },
        ],
        status: 'active',
        prize: 'Community bragging rights + custom badge',
        category: 'Fitness',
      },
    ],
  },
  {
    id: 'room-002',
    name: 'Book Club Elite',
    description: 'Monthly book discussions, reading challenges, and recommendation sharing for voracious readers.',
    category: 'Reading',
    memberCount: 18,
    members: ['user-001', 'user-004'],
    posts: [
      {
        id: 'post-004',
        userId: 'user-004',
        userName: 'Maya Torres',
        content: 'This month we are reading "Deep Work" by Cal Newport. Who is joining? Drop a comment if you are in!',
        createdAt: '2026-02-14T10:00:00.000Z',
        likes: 9,
        likedBy: ['user-001'],
        type: 'update',
      },
      {
        id: 'post-005',
        userId: 'user-001',
        userName: 'Alex Chen',
        content: 'Just finished "Atomic Habits". The chapter on identity-based habits changed my perspective completely. Highly recommend.',
        createdAt: '2026-02-12T16:30:00.000Z',
        likes: 15,
        likedBy: ['user-004'],
        type: 'milestone',
      },
    ],
    createdAt: '2025-10-15T00:00:00.000Z',
    isPublic: true,
    icon: 'FiBookOpen',
    type: 'community',
    challenges: [
      {
        id: 'ch-002',
        roomId: 'room-002',
        title: 'February Page Turner',
        description: 'Read 1,000 pages total in February. Track your daily pages and share your progress.',
        creatorName: 'Maya Torres',
        startDate: '2026-02-01T00:00:00.000Z',
        endDate: '2026-02-28T00:00:00.000Z',
        verificationMethod: 'self_report',
        participants: [
          {
            userId: 'user-001',
            userName: 'Alex Chen',
            joinedAt: '2026-02-01T10:00:00.000Z',
            progress: 55,
            completedMilestones: ['cm-004'],
            verified: false,
          },
        ],
        milestones: [
          {
            id: 'cm-004',
            title: '250 Pages',
            description: 'Read your first 250 pages',
            dueDate: '2026-02-07T00:00:00.000Z',
            verificationRequired: false,
          },
          {
            id: 'cm-005',
            title: '500 Pages',
            description: 'Halfway to 1,000 pages',
            dueDate: '2026-02-14T00:00:00.000Z',
            verificationRequired: false,
          },
          {
            id: 'cm-006',
            title: '1,000 Pages',
            description: 'Complete the full challenge',
            dueDate: '2026-02-28T00:00:00.000Z',
            verificationRequired: true,
          },
        ],
        status: 'active',
        category: 'Reading',
      },
    ],
  },
  {
    id: 'room-003',
    name: 'Morning Routine Masters',
    description: 'Build the perfect morning routine. Share what works, troubleshoot what does not, and hold each other accountable.',
    category: 'Wellness',
    memberCount: 32,
    members: ['user-005', 'user-006'],
    posts: [
      {
        id: 'post-006',
        userId: 'user-005',
        userName: 'Taylor Kim',
        content: 'My 5 AM routine: cold shower, 10 min meditation, 20 min journaling. Day 30 and I have never felt better.',
        createdAt: '2026-02-17T05:30:00.000Z',
        likes: 22,
        likedBy: [],
        type: 'update',
      },
      {
        id: 'post-007',
        userId: 'user-006',
        userName: 'Morgan Reeves',
        content: 'To everyone struggling to wake up early: try putting your phone across the room. Game changer.',
        createdAt: '2026-02-16T06:00:00.000Z',
        likes: 18,
        likedBy: [],
        type: 'encouragement',
      },
    ],
    createdAt: '2025-09-01T00:00:00.000Z',
    isPublic: true,
    icon: 'FiStar',
    type: 'community',
    challenges: [
      {
        id: 'ch-003',
        roomId: 'room-003',
        title: '21-Day Wake Up Challenge',
        description: 'Wake up before 6 AM for 21 consecutive days. Post your wake-up time daily.',
        creatorName: 'Taylor Kim',
        startDate: '2026-02-10T00:00:00.000Z',
        endDate: '2026-03-02T00:00:00.000Z',
        verificationMethod: 'photo',
        participants: [
          {
            userId: 'user-005',
            userName: 'Taylor Kim',
            joinedAt: '2026-02-10T05:00:00.000Z',
            progress: 40,
            completedMilestones: ['cm-007'],
            verified: true,
          },
        ],
        milestones: [
          {
            id: 'cm-007',
            title: 'Week 1',
            description: '7 consecutive early mornings',
            dueDate: '2026-02-17T00:00:00.000Z',
            verificationRequired: true,
          },
          {
            id: 'cm-008',
            title: 'Full 21 Days',
            description: 'Complete the challenge',
            dueDate: '2026-03-02T00:00:00.000Z',
            verificationRequired: true,
          },
        ],
        status: 'active',
        category: 'Wellness',
      },
    ],
  },
  {
    id: 'room-004',
    name: 'Side Project Builders',
    description: 'For those working on passion projects alongside their day jobs. Share progress, get feedback, stay on track.',
    category: 'Career',
    memberCount: 15,
    members: ['user-007'],
    posts: [
      {
        id: 'post-008',
        userId: 'user-007',
        userName: 'Casey Nakamura',
        content: 'Finally launched my personal portfolio site after 3 months of weekend work. Proof that slow and steady gets it done!',
        createdAt: '2026-02-13T20:00:00.000Z',
        likes: 11,
        likedBy: [],
        type: 'milestone',
      },
    ],
    createdAt: '2025-11-15T00:00:00.000Z',
    isPublic: true,
    icon: 'FiTarget',
    type: 'creator',
    creatorId: 'user-007',
    creatorName: 'Casey Nakamura',
    challenges: [
      {
        id: 'ch-004',
        roomId: 'room-004',
        title: 'Ship Something in February',
        description: 'Launch, publish, or release one tangible thing by end of February. No perfectionism allowed.',
        creatorName: 'Casey Nakamura',
        startDate: '2026-02-01T00:00:00.000Z',
        endDate: '2026-02-28T00:00:00.000Z',
        verificationMethod: 'supporter',
        participants: [
          {
            userId: 'user-007',
            userName: 'Casey Nakamura',
            joinedAt: '2026-02-01T09:00:00.000Z',
            progress: 80,
            completedMilestones: ['cm-009', 'cm-010'],
            verified: true,
          },
        ],
        milestones: [
          {
            id: 'cm-009',
            title: 'Define Your Ship',
            description: 'Clearly define what you are going to ship',
            dueDate: '2026-02-05T00:00:00.000Z',
            verificationRequired: false,
          },
          {
            id: 'cm-010',
            title: 'MVP Complete',
            description: 'Have a working minimum viable product',
            dueDate: '2026-02-20T00:00:00.000Z',
            verificationRequired: true,
          },
          {
            id: 'cm-011',
            title: 'Ship It',
            description: 'Launch or publish your project',
            dueDate: '2026-02-28T00:00:00.000Z',
            verificationRequired: true,
          },
        ],
        status: 'active',
        prize: 'Featured on GroPact community showcase',
        category: 'Career',
      },
    ],
  },
]

export const ENCOURAGEMENT_TEMPLATES: EncouragementTemplate[] = [
  { id: 'et-01', text: 'You are doing amazing! Keep going!', category: 'motivation' },
  { id: 'et-02', text: 'Every step counts, no matter how small.', category: 'motivation' },
  { id: 'et-03', text: 'Incredible milestone! You should be proud.', category: 'celebration' },
  { id: 'et-04', text: 'Way to crush it this week!', category: 'celebration' },
  { id: 'et-05', text: 'Setbacks are setups for comebacks. You got this.', category: 'comeback' },
  { id: 'et-06', text: 'One bad day does not erase your progress. Show up tomorrow.', category: 'comeback' },
  { id: 'et-07', text: 'New streak unlocked! Keep that momentum rolling.', category: 'milestone' },
  { id: 'et-08', text: 'Your consistency is inspiring. Keep building.', category: 'motivation' },
  { id: 'et-09', text: 'Remember why you started. You are closer than you think.', category: 'comeback' },
  { id: 'et-10', text: 'Another goal completed! The compound effect is real.', category: 'milestone' },
]

export const SUPPORTER_ACTIVITY_FEED: SupporterActivity[] = [
  {
    id: 'sa-001',
    type: 'encouragement',
    supporterName: 'Jordan',
    pactTitle: 'Run a 5K in Under 30 Minutes',
    pactId: 'pact-001',
    content: 'Great tempo run yesterday! Your pace is really improving.',
    createdAt: '2026-02-18T08:00:00.000Z',
  },
  {
    id: 'sa-002',
    type: 'verification',
    supporterName: 'Sam',
    pactTitle: 'Run a 5K in Under 30 Minutes',
    pactId: 'pact-001',
    content: 'Verified your stretching session completion.',
    createdAt: '2026-02-18T07:30:00.000Z',
  },
  {
    id: 'sa-003',
    type: 'encouragement',
    supporterName: 'Maya',
    pactTitle: 'Read 12 Books This Year',
    pactId: 'pact-002',
    content: 'Loved your summary of the habit loops chapter! Deep insights.',
    createdAt: '2026-02-17T21:00:00.000Z',
  },
  {
    id: 'sa-004',
    type: 'nudge',
    supporterName: 'Jordan',
    pactTitle: 'Run a 5K in Under 30 Minutes',
    pactId: 'pact-001',
    content: 'Have you done your intervals yet this week? Thursday is coming up!',
    createdAt: '2026-02-17T15:00:00.000Z',
  },
  {
    id: 'sa-005',
    type: 'reaction',
    supporterName: 'Riley',
    pactTitle: 'Learn Guitar Basics',
    pactId: 'pact-003',
    content: 'Reacted to your progress card: Guitar Basics Mastered',
    createdAt: '2026-02-16T12:00:00.000Z',
  },
  {
    id: 'sa-006',
    type: 'encouragement',
    supporterName: 'Maya',
    pactTitle: 'Read 12 Books This Year',
    pactId: 'pact-002',
    content: 'Your consistency is inspiring. Keep building that reading habit!',
    createdAt: '2026-02-15T18:00:00.000Z',
  },
  {
    id: 'sa-007',
    type: 'verification',
    supporterName: 'Jordan',
    pactTitle: 'Run a 5K in Under 30 Minutes',
    pactId: 'pact-001',
    content: 'Verified your 3K tempo run -- amazing time!',
    createdAt: '2026-02-14T19:00:00.000Z',
  },
]

export const PREMIUM_FEATURES: { name: string; description: string; tier: 'mid' | 'premium' }[] = [
  { name: 'Unlimited Pacts', description: 'Create as many pacts as you need', tier: 'mid' },
  { name: 'Weekly AI Reviews', description: 'AI-powered weekly progress reviews', tier: 'mid' },
  { name: 'Advanced Check-in Analytics', description: 'Detailed analytics on your check-in patterns', tier: 'mid' },
  { name: 'Priority Support', description: 'Faster response times from our team', tier: 'mid' },
  { name: 'AI Goal Architect (Full)', description: 'Unlimited AI-generated micro-goals and plans', tier: 'premium' },
  { name: 'Unlimited Supporters', description: 'Add as many supporters as you need', tier: 'premium' },
  { name: 'Verification Engine', description: 'Full multi-method verification system', tier: 'premium' },
  { name: 'Progress Cards', description: 'Generate and share shareable progress cards', tier: 'premium' },
  { name: 'Creator Challenge Tools', description: 'Create and manage room challenges', tier: 'premium' },
  { name: 'Team Dashboard', description: 'Manage team accountability at scale', tier: 'premium' },
  { name: 'Custom Rooms', description: 'Create private, branded community rooms', tier: 'premium' },
  { name: 'AI Blueprint Export', description: 'Export all AI plans as structured blueprints', tier: 'premium' },
]
