import type { User, Pact, Room } from './types'

export const MOCK_USER: User = {
  id: 'user-001',
  name: 'Alex Chen',
  email: 'alex@gropact.com',
  bio: 'Lifelong learner building better habits, one pact at a time.',
  joinedDate: '2025-12-01T00:00:00.000Z',
  currentStreak: 4,
  longestStreak: 12,
  completionRate: 72,
  totalPacts: 3,
  completedPacts: 1,
}

export const MOCK_PACTS: Pact[] = [
  {
    id: 'pact-001',
    userId: 'user-001',
    title: 'Run a 5K in Under 30 Minutes',
    description: 'Train consistently to improve my running pace and endurance, building up to completing a 5K race in under 30 minutes by the end of the month.',
    identityStatement: 'I am a dedicated runner who shows up for myself, rain or shine.',
    startDate: '2026-02-01T00:00:00.000Z',
    endDate: '2026-03-01T00:00:00.000Z',
    status: 'active',
    category: 'Fitness',
    supporters: [
      {
        id: 'sup-001',
        name: 'Jordan',
        feedback: 'Great progress on your intervals! Keep pushing the pace gradually.',
        addedDate: '2026-02-01T00:00:00.000Z',
      },
      {
        id: 'sup-002',
        name: 'Sam',
        feedback: 'Remember to warm up properly, you seemed tight last session.',
        addedDate: '2026-02-02T00:00:00.000Z',
      },
    ],
    microGoals: [
      {
        id: 'mg-001',
        goalText: 'Complete a 3K tempo run at target 5K pace',
        difficulty: 'medium',
        dueDate: '2026-02-20T00:00:00.000Z',
        reasoning: 'Building pace awareness at race speed will prepare your body for sustained effort.',
        measurableOutcome: 'Finish 3K in under 18 minutes',
        completed: true,
        completedDate: '2026-02-19T00:00:00.000Z',
      },
      {
        id: 'mg-002',
        goalText: 'Do 6x400m interval sprints with 90s rest',
        difficulty: 'hard',
        dueDate: '2026-02-22T00:00:00.000Z',
        reasoning: 'High-intensity intervals improve VO2 max and leg turnover speed.',
        measurableOutcome: 'Complete all 6 intervals under 1:50 each',
        completed: false,
      },
      {
        id: 'mg-003',
        goalText: 'Perform 20 minutes of dynamic stretching and foam rolling',
        difficulty: 'easy',
        dueDate: '2026-02-19T00:00:00.000Z',
        reasoning: 'Recovery prevents injury and keeps momentum going.',
        measurableOutcome: 'Complete full stretching routine without skipping',
        completed: true,
        completedDate: '2026-02-18T00:00:00.000Z',
      },
      {
        id: 'mg-004',
        goalText: 'Run a full 5K at comfortable pace',
        difficulty: 'medium',
        dueDate: '2026-02-24T00:00:00.000Z',
        reasoning: 'Distance practice builds endurance and mental confidence.',
        measurableOutcome: 'Complete 5K without walking breaks',
        completed: false,
      },
    ],
    nudges: [
      { nudgeText: 'Lay out your running gear the night before -- removing friction makes starting easier.', behavioralPrinciple: 'Friction Reduction' },
      { nudgeText: 'After each run, write one sentence about how you felt. Tracking emotions builds intrinsic motivation.', behavioralPrinciple: 'Reflective Practice' },
      { nudgeText: 'Tell Jordan your next run time so they can check in with you afterward.', behavioralPrinciple: 'Social Accountability' },
    ],
    weeklyPlan: [
      { day: 'Monday', microGoal: 'Dynamic stretching and foam rolling (20 min)', reminder: 'Recovery is training too. Your muscles need this.', supporterPrompt: 'Ask Sam for stretching tips they mentioned.', completed: true },
      { day: 'Tuesday', microGoal: 'Tempo run: 3K at target pace', reminder: 'Focus on breathing rhythm, not speed at the start.', supporterPrompt: 'Share your time with Jordan after the run.', completed: true },
      { day: 'Wednesday', microGoal: 'Rest day with light walking', reminder: 'Rest is strategic, not lazy. Trust the process.', supporterPrompt: 'Check in with your supporters about how you feel.', completed: true },
      { day: 'Thursday', microGoal: 'Interval sprints: 6x400m', reminder: 'Push hard on sprints, recover fully between sets.', supporterPrompt: 'Ask Jordan to join you for this session if possible.', completed: false },
      { day: 'Friday', microGoal: 'Easy 2K jog and stretching', reminder: 'Keep it light today. Tomorrow is your big run.', supporterPrompt: 'Let Sam know you are on track this week.', completed: false },
      { day: 'Saturday', microGoal: 'Full 5K run at comfortable pace', reminder: 'This is your confidence builder. No pressure on time.', supporterPrompt: 'Invite Jordan and Sam to cheer you on or join!', completed: false },
      { day: 'Sunday', microGoal: 'Rest and reflection', reminder: 'Write about your week. Celebrate what you achieved.', supporterPrompt: 'Share your weekly summary with your supporters.', completed: false },
    ],
    checkIns: [
      {
        id: 'ci-001',
        date: '2026-02-17T00:00:00.000Z',
        note: 'Ran 2.5K in 16 min. Felt strong on the first half but faded a bit.',
        mood: 'good',
        completedGoals: ['mg-003'],
      },
      {
        id: 'ci-002',
        date: '2026-02-16T00:00:00.000Z',
        note: 'Completed interval training. Legs were burning but pushed through all sets.',
        mood: 'great',
        completedGoals: [],
      },
      {
        id: 'ci-003',
        date: '2026-02-15T00:00:00.000Z',
        note: 'Rested due to rain. Did some indoor stretching instead.',
        mood: 'okay',
        completedGoals: [],
      },
    ],
    aiPlan: {
      behavioralState: 'consistent',
      identityAffirmation: 'You are a dedicated runner who shows up for yourself, rain or shine. Your consistency over the past 4 days proves that this goal is not just a wish -- it is who you are becoming.',
      microGoals: [],
      nudges: [],
      weeklyPlan: [],
      explanations: {
        pactInterpretation: 'Your pact focuses on progressive running improvement with a clear time-based target.',
        behaviorInsights: 'Your 4-day streak and 72% completion rate indicate a consistent pattern with occasional dips.',
        supporterInsights: 'Jordan provides performance-focused encouragement while Sam offers practical safety advice.',
      },
      difficultyDistribution: { easyPercent: 25, mediumPercent: 50, hardPercent: 25 },
    },
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-02-17T00:00:00.000Z',
    streak: 4,
    completionRate: 50,
    behavioralState: 'consistent',
    identityAffirmation: 'You are a dedicated runner who shows up for yourself, rain or shine.',
  },
  {
    id: 'pact-002',
    userId: 'user-001',
    title: 'Read 12 Books This Year',
    description: 'Build a consistent reading habit by finishing one book per month, focusing on personal growth and science topics.',
    identityStatement: 'I am a curious reader who invests in knowledge every day.',
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T00:00:00.000Z',
    status: 'active',
    category: 'Learning',
    supporters: [
      {
        id: 'sup-003',
        name: 'Maya',
        feedback: 'Love your book picks! Have you considered Atomic Habits? It ties into your goals.',
        addedDate: '2026-01-05T00:00:00.000Z',
      },
    ],
    microGoals: [
      {
        id: 'mg-005',
        goalText: 'Read 30 pages per day for 7 consecutive days',
        difficulty: 'medium',
        dueDate: '2026-02-25T00:00:00.000Z',
        reasoning: 'Consistent daily reading builds the habit loop.',
        measurableOutcome: '210 pages read by end of week',
        completed: false,
      },
      {
        id: 'mg-006',
        goalText: 'Write a one-paragraph summary of current book chapter',
        difficulty: 'easy',
        dueDate: '2026-02-21T00:00:00.000Z',
        reasoning: 'Summarizing deepens comprehension and retention.',
        measurableOutcome: 'Written summary shared with Maya',
        completed: true,
        completedDate: '2026-02-20T00:00:00.000Z',
      },
      {
        id: 'mg-007',
        goalText: 'Finish current book and start next one',
        difficulty: 'hard',
        dueDate: '2026-02-28T00:00:00.000Z',
        reasoning: 'Transitioning between books keeps momentum and excitement.',
        measurableOutcome: 'Book 2 completed, Book 3 started',
        completed: false,
      },
    ],
    nudges: [
      { nudgeText: 'Keep your current book on your nightstand so it is the last thing you see before sleep.', behavioralPrinciple: 'Environment Design' },
      { nudgeText: 'Replace 15 minutes of scrolling with reading after lunch.', behavioralPrinciple: 'Habit Stacking' },
    ],
    weeklyPlan: [
      { day: 'Monday', microGoal: 'Read 30 pages', reminder: 'Start with just one page. Momentum will carry you.', supporterPrompt: 'Tell Maya what chapter you are on.', completed: true },
      { day: 'Tuesday', microGoal: 'Read 30 pages', reminder: 'Try reading at a new location today.', supporterPrompt: 'Share a quote you liked.', completed: true },
      { day: 'Wednesday', microGoal: 'Read 30 pages and write a summary', reminder: 'Summarizing what you read cements it.', supporterPrompt: 'Send your summary to Maya.', completed: false },
      { day: 'Thursday', microGoal: 'Read 30 pages', reminder: 'Consistency over intensity.', supporterPrompt: 'Ask Maya for recommendations.', completed: false },
      { day: 'Friday', microGoal: 'Read 30 pages', reminder: 'Almost done for the week!', supporterPrompt: 'Share your progress update.', completed: false },
      { day: 'Saturday', microGoal: 'Finish remaining chapters or free read', reminder: 'Enjoy the journey.', supporterPrompt: 'Discuss the book with Maya.', completed: false },
      { day: 'Sunday', microGoal: 'Reflect and plan next book', reminder: 'What did this book teach you?', supporterPrompt: 'Post a mini review for the group.', completed: false },
    ],
    checkIns: [
      {
        id: 'ci-004',
        date: '2026-02-17T00:00:00.000Z',
        note: 'Read 35 pages today. The chapter on habit loops was fascinating.',
        mood: 'great',
        completedGoals: ['mg-006'],
      },
      {
        id: 'ci-005',
        date: '2026-02-15T00:00:00.000Z',
        note: 'Only managed 15 pages but took detailed notes.',
        mood: 'okay',
        completedGoals: [],
      },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-02-17T00:00:00.000Z',
    streak: 2,
    completionRate: 33,
  },
  {
    id: 'pact-003',
    userId: 'user-001',
    title: 'Learn Guitar Basics',
    description: 'Learn fundamental guitar chords, strumming patterns, and play 3 songs from start to finish.',
    identityStatement: 'I am a musician who embraces the learning process with patience.',
    startDate: '2025-12-01T00:00:00.000Z',
    endDate: '2026-01-31T00:00:00.000Z',
    status: 'completed',
    category: 'Creative',
    supporters: [
      {
        id: 'sup-004',
        name: 'Riley',
        feedback: 'Your chord transitions are getting so much smoother!',
        addedDate: '2025-12-05T00:00:00.000Z',
      },
    ],
    microGoals: [
      {
        id: 'mg-008',
        goalText: 'Learn and memorize 5 basic open chords (C, G, D, Em, Am)',
        difficulty: 'medium',
        dueDate: '2025-12-15T00:00:00.000Z',
        reasoning: 'These chords form the foundation of thousands of songs.',
        measurableOutcome: 'Play all 5 chords from memory without hesitation',
        completed: true,
        completedDate: '2025-12-14T00:00:00.000Z',
      },
      {
        id: 'mg-009',
        goalText: 'Practice chord transitions for 15 minutes daily',
        difficulty: 'easy',
        dueDate: '2025-12-31T00:00:00.000Z',
        reasoning: 'Smooth transitions are key to playing actual songs.',
        measurableOutcome: 'Transition between any two chords in under 2 seconds',
        completed: true,
        completedDate: '2025-12-28T00:00:00.000Z',
      },
      {
        id: 'mg-010',
        goalText: 'Learn and perform 3 complete songs',
        difficulty: 'hard',
        dueDate: '2026-01-31T00:00:00.000Z',
        reasoning: 'Playing complete songs integrates all skills and builds confidence.',
        measurableOutcome: 'Record yourself playing 3 songs and share with Riley',
        completed: true,
        completedDate: '2026-01-29T00:00:00.000Z',
      },
    ],
    nudges: [
      { nudgeText: 'Keep your guitar on a stand in your living room, not in a case.', behavioralPrinciple: 'Friction Reduction' },
      { nudgeText: 'Practice right after your morning coffee for habit consistency.', behavioralPrinciple: 'Habit Stacking' },
    ],
    weeklyPlan: [
      { day: 'Monday', microGoal: 'Chord practice (15 min)', reminder: 'Focus on clean sound.', supporterPrompt: 'Show Riley your progress.', completed: true },
      { day: 'Tuesday', microGoal: 'Strumming patterns (15 min)', reminder: 'Keep a steady rhythm.', supporterPrompt: 'Ask Riley for song suggestions.', completed: true },
      { day: 'Wednesday', microGoal: 'Song practice (20 min)', reminder: 'Slow is smooth, smooth is fast.', supporterPrompt: 'Share a short clip.', completed: true },
      { day: 'Thursday', microGoal: 'Chord transitions (15 min)', reminder: 'Focus on the difficult ones.', supporterPrompt: 'Check in with Riley.', completed: true },
      { day: 'Friday', microGoal: 'Full song run-through', reminder: 'Play through mistakes.', supporterPrompt: 'Perform for someone.', completed: true },
      { day: 'Saturday', microGoal: 'Learn a new technique', reminder: 'Try fingerpicking.', supporterPrompt: 'Discuss new goals.', completed: true },
      { day: 'Sunday', microGoal: 'Free play and reflect', reminder: 'Enjoy the music.', supporterPrompt: 'Share your week.', completed: true },
    ],
    checkIns: [],
    createdAt: '2025-12-01T00:00:00.000Z',
    updatedAt: '2026-01-29T00:00:00.000Z',
    streak: 0,
    completionRate: 100,
    behavioralState: 'consistent',
  },
]

export const MOCK_ROOMS: Room[] = [
  {
    id: 'room-001',
    name: 'Runners United',
    description: 'A supportive community for runners of all levels. Share your runs, get advice, and stay motivated together.',
    category: 'Fitness',
    memberCount: 24,
    members: ['user-001', 'user-002', 'user-003'],
    posts: [
      {
        id: 'post-001',
        userId: 'user-002',
        userName: 'Jordan Lee',
        content: 'Just finished my first half marathon! 2:15:30. Never thought I could do it when I started running 6 months ago. Keep pushing, everyone!',
        createdAt: '2026-02-17T14:30:00.000Z',
        likes: 12,
        likedBy: ['user-001', 'user-003'],
        type: 'milestone',
      },
      {
        id: 'post-002',
        userId: 'user-003',
        userName: 'Priya Sharma',
        content: 'Any tips for running in cold weather? I lose motivation when it drops below 5 degrees.',
        createdAt: '2026-02-16T09:15:00.000Z',
        likes: 5,
        likedBy: ['user-001'],
        type: 'question',
      },
      {
        id: 'post-003',
        userId: 'user-001',
        userName: 'Alex Chen',
        content: 'Hit a new 3K personal best today: 17:45! Interval training is really paying off.',
        createdAt: '2026-02-15T18:00:00.000Z',
        likes: 8,
        likedBy: ['user-002', 'user-003'],
        type: 'update',
      },
    ],
    createdAt: '2025-11-01T00:00:00.000Z',
    isPublic: true,
    icon: 'FiActivity',
  },
  {
    id: 'room-002',
    name: 'Book Club Elite',
    description: 'Monthly book discussions, reading challenges, and recommendation sharing for voracious readers.',
    category: 'Reading',
    memberCount: 18,
    members: ['user-001', 'user-004'],
    posts: [
      {
        id: 'post-004',
        userId: 'user-004',
        userName: 'Maya Torres',
        content: 'This month we are reading "Deep Work" by Cal Newport. Who is joining? Drop a comment if you are in!',
        createdAt: '2026-02-14T10:00:00.000Z',
        likes: 9,
        likedBy: ['user-001'],
        type: 'update',
      },
      {
        id: 'post-005',
        userId: 'user-001',
        userName: 'Alex Chen',
        content: 'Just finished "Atomic Habits". The chapter on identity-based habits changed my perspective completely. Highly recommend.',
        createdAt: '2026-02-12T16:30:00.000Z',
        likes: 15,
        likedBy: ['user-004'],
        type: 'milestone',
      },
    ],
    createdAt: '2025-10-15T00:00:00.000Z',
    isPublic: true,
    icon: 'FiBookOpen',
  },
  {
    id: 'room-003',
    name: 'Morning Routine Masters',
    description: 'Build the perfect morning routine. Share what works, troubleshoot what does not, and hold each other accountable.',
    category: 'Wellness',
    memberCount: 32,
    members: ['user-005', 'user-006'],
    posts: [
      {
        id: 'post-006',
        userId: 'user-005',
        userName: 'Taylor Kim',
        content: 'My 5 AM routine: cold shower, 10 min meditation, 20 min journaling. Day 30 and I have never felt better.',
        createdAt: '2026-02-17T05:30:00.000Z',
        likes: 22,
        likedBy: [],
        type: 'update',
      },
      {
        id: 'post-007',
        userId: 'user-006',
        userName: 'Morgan Reeves',
        content: 'To everyone struggling to wake up early: try putting your phone across the room. Game changer.',
        createdAt: '2026-02-16T06:00:00.000Z',
        likes: 18,
        likedBy: [],
        type: 'encouragement',
      },
    ],
    createdAt: '2025-09-01T00:00:00.000Z',
    isPublic: true,
    icon: 'FiStar',
  },
  {
    id: 'room-004',
    name: 'Side Project Builders',
    description: 'For those working on passion projects alongside their day jobs. Share progress, get feedback, stay on track.',
    category: 'Career',
    memberCount: 15,
    members: ['user-007'],
    posts: [
      {
        id: 'post-008',
        userId: 'user-007',
        userName: 'Casey Nakamura',
        content: 'Finally launched my personal portfolio site after 3 months of weekend work. Proof that slow and steady gets it done!',
        createdAt: '2026-02-13T20:00:00.000Z',
        likes: 11,
        likedBy: [],
        type: 'milestone',
      },
    ],
    createdAt: '2025-11-15T00:00:00.000Z',
    isPublic: true,
    icon: 'FiTarget',
  },
]
